apiVersion: v1
kind: Service
metadata:
  name: mermaid-test
  namespace: mermaid-test-namespace
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "9000"
spec:
  clusterIP: None
  ports:
    - name: grcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: mermaid-test
