// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/pinguo-icc/kratos-library/v2/trace"
	"github.com/pinguo-icc/mermaid-test/api"
	"github.com/pinguo-icc/mermaid-test/internal/application"
	"github.com/pinguo-icc/mermaid-test/internal/infrastructure/conf"
	"github.com/pinguo-icc/mermaid-test/internal/infrastructure/server"
)

import (
	_ "github.com/pinguo-icc/mermaid-test/internal/domain"
)

// Injectors from wire.go:

//initApp init kratos application.
//go:generate kratos t wire
func initApp(logger log.Logger, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	http := bootstrap.Http
	unsafeTemplateServer := _wireUnimplementedTemplateServerValue
	app := &application.App{
		UnsafeTemplateServer: unsafeTemplateServer,
	}
	config := bootstrap.Trace
	tracerProvider := trace.NewTracerProvider(config)
	httpServer := server.NewHTTPServer(http, logger, app, tracerProvider)
	grpc := bootstrap.Grpc
	grpcServer := server.NewGRPCServer(grpc, logger, app, tracerProvider)
	kratosApp := newApp(logger, httpServer, grpcServer)
	return kratosApp, func() {
	}, nil
}

var (
	_wireUnimplementedTemplateServerValue = new(api.UnimplementedTemplateServer)
)
