name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: set go version
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: set provite 
        run: go env -w GOPRIVATE="github.com/pinguo-icc/*"  GONOPROXY="github.com/pinguo-icc/*" GONOSUMDB="github.com/pinguo-icc/*" && go env
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - name: set git
        run: echo machine github.com login ${{ secrets.ACTION_NAME }} password ${{ secrets.ACTION_TOKEN }} > /$HOME/.netrc
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: --config=${{ github.workspace }}/.github/.golangci.yaml
          only-new-issues: true
          github-token: ${{ secrets.ACTION_TOKEN }}